export const SHOW_USERS_LOADING = 'SHOW_USERS_LOADING'
export const HIDE_USERS_LOADING = 'HIDE_USERS_LOADING'
export const SHOW_QUESTIONS_LOADING = 'SHOW_QUESTIONS_LOADING'
export const HIDE_QUESTIONS_LOADING = 'HIDE_QUESTIONS_LOADING'